/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mil.af.weather;

import com.offbytwo.jenkins.model.Build;
import com.offbytwo.jenkins.model.BuildResult;
import com.offbytwo.jenkins.model.BuildWithDetails;
import com.offbytwo.jenkins.model.Job;
import java.awt.Cursor;
import java.io.IOException;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Blake Bartenbach
 */
public class BuildDowntimeAnalyzer extends javax.swing.JFrame {

    /**
     * Global variable containing a map of all jobs on the Jenkins server. (this
     * data structure is returned by the Jenkins API)
     */
    private final Map<String, Job> jobMap;
    /**
     * Variable holding the currently selected job.
     */
    private Job currentlySelectedJob;
    /**
     * Holds all builds that are currently in the buildList.
     */
    private List<Build> buildListContents = new ArrayList<>();

    /**
     * Creates new form BuildDowntimeAnalyzer
     *
     * @param jobMap - The map of all jobs on the Jenkins server
     */
    public BuildDowntimeAnalyzer(Map<String, Job> jobMap) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildDowntimeAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, "Failed to load UI of BuildDowntimeAnalyzer");
        }
        this.jobMap = jobMap;
        initComponents();
        // set everything in the UI up with some sane defaults for the user to see
        listJenkinsJobs.setListData(jobMap.keySet().toArray(new String[0]));
        listJenkinsBuilds.setListData(new String[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJenkinsJobs = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textBuildDowntime = new javax.swing.JTextField();
        textBuildUptime = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        listJenkinsBuilds = new javax.swing.JList<>();
        btnSelectAll = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textUptimePercentage = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Build Downtime Analyzer");

        jLabel1.setText("Jobs");

        listJenkinsJobs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listJenkinsJobs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listJenkinsJobs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listJenkinsJobsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listJenkinsJobs);

        jLabel2.setText("Builds");

        jLabel3.setText("Total Build Downtime:");

        jLabel4.setText("Total Build Uptime:");

        listJenkinsBuilds.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listJenkinsBuilds.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        listJenkinsBuilds.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listJenkinsBuildsValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listJenkinsBuilds);

        btnSelectAll.setText("Select All");
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel5.setText("Uptime Percentage:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textBuildDowntime, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(textBuildUptime)
                            .addComponent(textUptimePercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectAll)
                .addGap(34, 34, 34)
                .addComponent(btnClear)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectAll)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textBuildDowntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textBuildUptime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textUptimePercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listJenkinsJobsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listJenkinsJobsValueChanged
        // this line is required or the event triggers twice.
        if (evt.getValueIsAdjusting()) {
            return;
        }
        this.getComponent(0).setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        this.currentlySelectedJob = jobMap.get(listJenkinsJobs.getSelectedValue());
        List<String> buildsToDisplay = new ArrayList<>();
        try {
            this.buildListContents = this.currentlySelectedJob.details().getAllBuilds();
            for (int i = 0; i < this.buildListContents.size(); i++) {
                // TODO add the status here too
                BuildWithDetails currentBuild = this.buildListContents.get(i).details();
                String dateStamp = DateFormat.getDateInstance(DateFormat.LONG).format(new Date(currentBuild.getTimestamp()));
                String timeStamp = DateFormat.getTimeInstance(DateFormat.LONG).format(new Date(currentBuild.getTimestamp()));
                String id = currentBuild.getId();
                String status = currentBuild.getResult().toString();
                buildsToDisplay.add("(" + id + ") " + dateStamp + " " + timeStamp + " [" + status + "]");
            }
        } catch (IOException ex) {
            Logger.getLogger(BuildDowntimeAnalyzer.class.getName()).log(Level.SEVERE, "Failed to get all builds for job: {0}", this.currentlySelectedJob.getName());
            JOptionPane.showMessageDialog(null, "An error was encountered getting all the builds for job: " + this.currentlySelectedJob, "Error", JOptionPane.ERROR_MESSAGE);
            this.getComponent(0).setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        System.out.println("Adding " + buildsToDisplay.size() + " to build list");
        listJenkinsBuilds.setListData(buildsToDisplay.toArray(new String[0]));
        this.getComponent(0).setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_listJenkinsJobsValueChanged

    private void listJenkinsBuildsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listJenkinsBuildsValueChanged
        // prevent event from firing twice
        if (evt.getValueIsAdjusting()) {
            return;
        }
        if (listJenkinsBuilds.getSelectedValuesList().size() <= 1) {
            // not enough builds are selected
            textBuildDowntime.setText("");
            textBuildUptime.setText("");
            textUptimePercentage.setText("");
            return;
        }
        if (buildListContents.size() <= 1) {
            // show dialog that there's nothing to compare
            JOptionPane.showMessageDialog(null, "Not enough builds to compare.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.getComponent(0).setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        // get all builds the user selected
        int[] indices = listJenkinsBuilds.getSelectedIndices();
        List<BuildWithDetails> selectedBuilds = new ArrayList<>();
        
        for (int i : indices) {
            try {
                selectedBuilds.add(this.buildListContents.get(i).details());
            } catch (IOException ex) {
                Logger.getLogger(BuildDowntimeAnalyzer.class.getName()).log(Level.SEVERE, "Failed to get build details.");
            }
        }

        BuildWithDetails build, nextBuild;
        BuildMetrics metrics = new BuildMetrics();
        BuildResult status;

        for (int i = 0; i < selectedBuilds.size() - 1; i++) {
            build = selectedBuilds.get(i);
            nextBuild = selectedBuilds.get(i+1);
            if (build.isBuilding() || nextBuild.isBuilding()) {
                JOptionPane.showMessageDialog(null, "One of the selected builds is still building which may skew statistics.",
                        "Warning", JOptionPane.WARNING_MESSAGE);
            }
            status = nextBuild.getResult();
            switch (status) {
                case FAILURE:
                    metrics.addDowntime(build.getTimestamp() - nextBuild.getTimestamp());
                    break;
                case SUCCESS:
                    metrics.addUptime(build.getTimestamp() - nextBuild.getTimestamp());
                    break;
            }
        }
        String formattedDowntime = String.format("%02d hours %02d minutes %02d seconds", TimeUnit.MILLISECONDS.toHours(metrics.getDowntime()),
                TimeUnit.MILLISECONDS.toMinutes(metrics.getDowntime()) % TimeUnit.HOURS.toMinutes(1),
                TimeUnit.MILLISECONDS.toSeconds(metrics.getDowntime()) % TimeUnit.MINUTES.toSeconds(1));
        String formattedUptime = String.format("%02d hours %02d minutes %02d seconds", TimeUnit.MILLISECONDS.toHours(metrics.getUptime()),
                TimeUnit.MILLISECONDS.toMinutes(metrics.getUptime()) % TimeUnit.HOURS.toMinutes(1),
                TimeUnit.MILLISECONDS.toSeconds(metrics.getUptime()) % TimeUnit.MINUTES.toSeconds(1));
        
        textBuildDowntime.setText(formattedDowntime);
        textBuildUptime.setText(String.valueOf(formattedUptime));
        
        // uptime percentage calculation
        double downtimePercentage = (double) metrics.getDowntime() / metrics.getTotalTime();
        double uptimePercentage = 1 - downtimePercentage;
        NumberFormat nf = NumberFormat.getPercentInstance();
        nf.setMaximumFractionDigits(2);
        nf.setMinimumFractionDigits(1);
        textUptimePercentage.setText(nf.format(uptimePercentage));
        
        // done waiting
        this.getComponent(0).setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_listJenkinsBuildsValueChanged

    private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
        listJenkinsBuilds.setSelectionInterval(0, this.buildListContents.size() - 1);
    }//GEN-LAST:event_btnSelectAllActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        listJenkinsBuilds.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> listJenkinsBuilds;
    private javax.swing.JList<String> listJenkinsJobs;
    private javax.swing.JTextField textBuildDowntime;
    private javax.swing.JTextField textBuildUptime;
    private javax.swing.JTextField textUptimePercentage;
    // End of variables declaration//GEN-END:variables
}
